version: '3.8'
services:
  web:
    build: .
    command: gunicorn -w 4 -k gthread --bind 0.0.0.0:8000 app:app
    environment:
      - ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/caixa
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - .:/app:ro

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: caixa
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
